dependencies:
  - name: mongodb
    version: "> 7.10.2"
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: mongodb.enabled
  - name: postgresql
    version: ">= 0"
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: postgresql.enabled