dependencies:
  - name: mongodb
    # Versions above 7.8 (<7.10.2) contains an error 
    version: "7.8.10"
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: mongodb.enabled
  - name: postgresql
    version: ">= 0"
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: postgresql.enabled