dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: postgresql.enabled
  - name: redis
    version: 11.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: redis.enabled
  - name: common
    version: 0.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo