dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: postgresql.enabled
  - name: redis
    version: 10.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: redis.enabled