dependencies:
  - name: postgresql
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 8.X.X
    condition: postgresql.enabled
  - name: redis
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 10.X.X
    condition: redis.enabled