dependencies:
  - name: common
    version: 0.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    tags:
      - bitnami-common
  - name: postgresql
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 9.X.X
    condition: postgresql.enabled
  - name: redis
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 11.X.X
    condition: redis.enabled