dependencies:
- name: mariadb
  version: 5.x.x
  repository: https://marketplace.azurecr.io/helm/v1/repo/
  condition: databaseType.mariadb
- name: postgresql
  version: 3.x.x
  repository: https://marketplace.azurecr.io/helm/v1/repo/
  condition: databaseType.postgresql