dependencies:
- name: mariadb
  version: 6.x.x
  repository: https://marketplace.azurecr.io/helm/v1/repo/
  condition: mariadb.enabled
- name: postgresql
  version: 6.x.x
  repository: https://marketplace.azurecr.io/helm/v1/repo/
  condition: postgresql.enabled