dependencies:
  - name: mariadb
    version: 7.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: mariadb.enabled
  - name: common
    version: 0.7.x
    repository: https://marketplace.azurecr.io/helm/v1/repo