dependencies:
  - name: mariadb
    version: 7.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo/
    condition: mariadb.enabled
  - name: elasticsearch
    version: 10.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: elasticsearch.enabled