dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 9.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
  - name: cassandra
    condition: cassandra.enabled
    version: 6.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
  - name: common
    version: 0.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo