dependencies:
  - name: common
    version: 0.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    tags:
      - bitnami-common
  - name: postgresql
    version: 9.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: postgresql.enabled