dependencies:
  - name: common
    version: 0.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    tags:
      - bitnami-common
  - name: kube-state-metrics
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 0.x.x
    condition: kube-state-metrics.enabled