dependencies:
  - name: common
    version: "^0.3.0"
    repository: https://marketplace.azurecr.io/helm/v1/repo
    tags:
      - bitnami-common
  - name: mariadb
    version: 7.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: db.bundleTestDB
    tags:
      - phpmyadmin-database