dependencies:
- name: postgresql
  version: 3.x.x
  repository: https://marketplace.azurecr.io/helm/v1/repo
  condition: postgresql.enabled
- name: redis
  version: 7.x.x
  repository: https://marketplace.azurecr.io/helm/v1/repo
  condition: redis.enabled