dependencies:
  - name: postgresql
    version: 6.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: postgresql.enabled
  - name: redis
    version: 9.x.x
    repository: https://marketplace.azurecr.io/helm/v1/repo
    condition: redis.enabled